name: Master build Docker

on:
  pull_request: # TODO: Switch to push before merge
    - master

env:
  OWNER: streamr
  IMAGE_NAME: engine-and-editor

jobs:
  unit-test:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: sdkman/sdkman-action@master
        id: sdkman
        with:
          candidate: java
          version: 8.0.275-zulu
      - uses: actions/setup-java@v1.4.3
        id: setup-java
        with:
          java-version: 8.0
          jdkFile: ${{ steps.sdkman.outputs.file }}
      - run: java --version
      - uses: sdkman/sdkman-action@master
        id: sdkman
        with:
          candidate: grails
          version: 2.5.6
      - run: grails --version
      - uses: actions/cache@v2.1.3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('grails-app/conf/BuildConfig.groovy') }}
          restore-keys: ${{ runner.os }}-maven
      - name: Build
        run: |
          make -f Makefile.ci compile
      - name: Unit Test
        run: |
          make -f Makefile.ci test-unit
  integration-test:
    name: Integration test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: sdkman/sdkman-action@master
        id: sdkman
        with:
          candidate: java
          version: 8.0.275-zulu
      - uses: actions/setup-java@v1.4.3
        id: setup-java
        with:
          java-version: 8.0
          jdkFile: ${{ steps.sdkman.outputs.file }}
      - run: java --version
      - uses: sdkman/sdkman-action@master
        id: sdkman
        with:
          candidate: grails
          version: 2.5.6
      - run: grails --version
      - uses: actions/cache@v2.1.3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('grails-app/conf/BuildConfig.groovy') }}
          restore-keys: ${{ runner.os }}-maven
      - name: Integration test
        run: |
          make -f Makefile.ci test-integration
  e2e-test:
    name: End to end test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: sdkman/sdkman-action@master
        id: sdkman
        with:
          candidate: java
          version: 8.0.275-zulu
      - uses: actions/setup-java@v1.4.3
        id: setup-java
        with:
          java-version: 8.0
          jdkFile: ${{ steps.sdkman.outputs.file }}
      - run: java --version
      - uses: sdkman/sdkman-action@master
        id: sdkman
        with:
          candidate: grails
          version: 2.5.6
      - run: grails --version
      - uses: actions/cache@v2.1.3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('grails-app/conf/BuildConfig.groovy') }}
          restore-keys: ${{ runner.os }}-maven
      - name: Set variables
        run: |
          echo "::set-env name=NODE_VERSION::$(cat rest-e2e-tests/.nvmrc)"
          echo "Node version: ${NODE_VERSION}"
      - name: Install Node
      - uses: actions/setup-node@v2.1.4
        with:
          node-version: ${NODE_VERSION}
      - name: Start Streamr Docker Stack
        uses: streamr-dev/streamr-docker-dev-action@v1.0.0-alpha.1
        with:
          services-to-start: 'mysql redis cassandra parity-node0 parity-sidechain-node0 bridge data-union-server broker-node-storage-1 nginx smtp'
      - name: Stop old E&E from Docker Hub
        run: streamr-docker-dev stop engine-and-editor
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1.1.1
      - name: Build Docker image
        uses: docker/build-push-action@v2.2.2
        with:
          context: .
          tags: streamr/engine-and-editor:dev
          file: ./Dockerfile
          platforms: linux/amd64
          push: false
      - name: Start locally built E&E
        run: |
          streamr-docker-dev start engine-and-editor
          streamr-docker-dev wait
      - name: End to End tests
        run: |
          cd rest-e2e-tests
          npm ci
          npm run test:e2e
  build-docker:
    name: Build Docker and push to Docker Hub
    needs:
      - unit-test
      - integration-test
      - e2e-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: sdkman/sdkman-action@master
        id: sdkman
        with:
          candidate: java
          version: 8.0.275-zulu
      - uses: actions/setup-java@v1.4.3
        id: setup-java
        with:
          java-version: 8.0
          jdkFile: ${{ steps.sdkman.outputs.file }}
      - run: java --version
      - uses: sdkman/sdkman-action@master
        id: sdkman
        with:
          candidate: grails
          version: 2.5.6
      - run: grails --version
      - uses: actions/cache@v2.1.3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('grails-app/conf/BuildConfig.groovy') }}
          restore-keys: ${{ runner.os }}-maven
      - name: Docker meta
        id: docker_meta
        uses: crazy-max/ghaction-docker-meta@v1.11.0
        with:
          images: streamr/grails-builder
          tag-sha: true
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1.1.1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2.2.2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          push: true
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}

