name: Master build Docker

on:
  pull_request: # TODO: Switch to push before merge

jobs:
  unit-test:
    name: Build and test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: sdkman/sdkman-action@master
        id: sdkman-java
        with:
          candidate: java
          version: 8.0.275-zulu
      - uses: actions/setup-java@v1.4.3
        id: setup-java
        with:
          java-version: 8.0
          jdkFile: ${{ steps.sdkman-java.outputs.file }}
      - uses: sdkman/sdkman-action@master
        id: sdkman-grails
        with:
          candidate: grails
          version: 2.5.6
      - uses: actions/cache@v2.1.3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('grails-app/conf/BuildConfig.groovy') }}
          restore-keys: ${{ runner.os }}-maven
      - name: Install Grails
        run: |
          echo "${{ steps.sdkman.outputs.file }}/bin" >> $GITHUB_PATH
      - name: Build
        run: |
          make -f Makefile.ci compile
      - name: Unit Test
        run: |
          make -f Makefile.ci test-unit
